//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCalculatorClient.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
    [System.SerializableAttribute()]
    public partial class CalculationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="bsuir.mpp/IvanShimko/2016/11", ConfigurationName="CalculatorService.Calculator")]
    public interface Calculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Add", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleCalculatorClient.CalculatorService.CalculationFault), Action="bsuir.mpp/IvanShimko/2016/11/Calculator/AddCalculationFaultFault", Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
        double Add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Add", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Substract", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/SubstractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleCalculatorClient.CalculatorService.CalculationFault), Action="bsuir.mpp/IvanShimko/2016/11/Calculator/SubstractCalculationFaultFault", Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
        double Substract(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Substract", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/SubstractResponse")]
        System.Threading.Tasks.Task<double> SubstractAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Multiply", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/MultiplyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleCalculatorClient.CalculatorService.CalculationFault), Action="bsuir.mpp/IvanShimko/2016/11/Calculator/MultiplyCalculationFaultFault", Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
        double Multiply(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Multiply", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Divide", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/DivideResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleCalculatorClient.CalculatorService.CalculationFault), Action="bsuir.mpp/IvanShimko/2016/11/Calculator/DivideCalculationFaultFault", Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
        double Divide(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Divide", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Sqrt", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/SqrtResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleCalculatorClient.CalculatorService.CalculationFault), Action="bsuir.mpp/IvanShimko/2016/11/Calculator/SqrtCalculationFaultFault", Name="CalculationFault", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
        double Sqrt(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="bsuir.mpp/IvanShimko/2016/11/Calculator/Sqrt", ReplyAction="bsuir.mpp/IvanShimko/2016/11/Calculator/SqrtResponse")]
        System.Threading.Tasks.Task<double> SqrtAsync(double a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorChannel : ConsoleCalculatorClient.CalculatorService.Calculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<ConsoleCalculatorClient.CalculatorService.Calculator>, ConsoleCalculatorClient.CalculatorService.Calculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double a, double b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double a, double b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double Substract(double a, double b) {
            return base.Channel.Substract(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SubstractAsync(double a, double b) {
            return base.Channel.SubstractAsync(a, b);
        }
        
        public double Multiply(double a, double b) {
            return base.Channel.Multiply(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double a, double b) {
            return base.Channel.MultiplyAsync(a, b);
        }
        
        public double Divide(double a, double b) {
            return base.Channel.Divide(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double a, double b) {
            return base.Channel.DivideAsync(a, b);
        }
        
        public double Sqrt(double a) {
            return base.Channel.Sqrt(a);
        }
        
        public System.Threading.Tasks.Task<double> SqrtAsync(double a) {
            return base.Channel.SqrtAsync(a);
        }
    }
}
